apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: busybox:1.28
    name: test-container1
    command: ["sleep","10000"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox:1.28
    name: test-container2
    command: ["sleep","10000"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi