apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: busybox:1.28
    name: test-container1
    command: ["sleep","10000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - image: busybox:1.28
    name: test-container2
    command: ["sleep","10000"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    persistentVolumeClaim:
      claimName: task-pvc-claim